# Generated by Django 5.2.6 on 2025-10-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diariomural', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariomural',
            name='slug',
            field=models.SlugField(default='', max_length=200),
        ),
    ]
