# Generated by Django 5.2.6 on 2025-10-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diariomural', '0002_diariomural_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='diariomural',
            name='imagen',
            field=models.ImageField(blank=True, default='sin_imagen.png', upload_to=''),
        ),
    ]
