# Generated by Django 5.2.8 on 2025-11-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diariomural', '0003_diariomural_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDiarioMural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='diariomural',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diariomural.estadodiariomural'),
        ),
    ]
