# Generated by Django 5.2.8 on 2025-11-06 19:39

from django.db import migrations

def create_default_estado(apps, schema_editor):
    EstadoDiarioMural = apps.get_model('diariomural', 'EstadoDiarioMural')
    DiarioMural = apps.get_model('diariomural', 'DiarioMural')
    
    # Crear lista de estados
    estados = [
        EstadoDiarioMural(nombre_estado='Activo', estado='A'),
        EstadoDiarioMural(nombre_estado='Inactivo', estado='I'),
        EstadoDiarioMural(nombre_estado='Borrador', estado='A'),
        EstadoDiarioMural(nombre_estado='Archivado', estado='I'),
    ]
    
    # Crear todos de una vez
    EstadoDiarioMural.objects.bulk_create(estados)
    
    # Obtener el primer estado creado para asignarlo
    estado_default = EstadoDiarioMural.objects.get(nombre_estado='Activo')
    
    # Asignar a todos los registros existentes
    DiarioMural.objects.filter(tipo__isnull=True).update(tipo=estado_default)


class Migration(migrations.Migration):

    dependencies = [
        ('diariomural', '0004_estadodiariomural_diariomural_tipo'),
    ]

    operations = [
        migrations.RunPython(create_default_estado),
    ]
