# Generated by Django 5.2.8 on 2025-11-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diariomural', '0005_auto_20251106_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariomural',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='diariomural.estadodiariomural'),
        ),
    ]
