# Generated by Django 5.2.8 on 2025-11-06 20:02

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diariomural', '0006_alter_diariomural_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariomural',
            name='imagen',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='sin_imagen.png', force_format='PNG', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to=''),
        ),
    ]
