# Generated by Django 5.2.8 on 2025-11-11 12:24

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diariomural', '0007_alter_diariomural_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diariomural',
            name='imagen',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='sin_imagen.png', force_format='WEBP', keep_meta=False, quality=75, scale=None, size=[300, 300], upload_to='diario_mural/%Y/%m/'),
        ),
    ]
